OTEL_SERVICE_NAME = "news-retrieval-agent"


OPENAI_EMBEDDING_TIMEOUT_SECONDS = 60
OPENAI_EMBEDDING_MAX_RETRIES = 3

CHROMA_BATCH_SIZE = 128
CHROMA_SCHEMA_VERSION = "1"
CHROMA_DISTANCE_METRIC = "cosine"
CHROMA_TOKEN_ENCODING = "cl100k_base"
CHROMA_CHUNK_TARGET_TOKENS = 500
CHROMA_CHUNK_MIN_TOKENS = 400
CHROMA_CHUNK_MAX_TOKENS = 600
CHROMA_OVERLAP_TARGET_TOKENS = 100
FACTS_ACTIVE_COLLECTION = "facts"
FACTS_STAGING_COLLECTION = "facts_staging"
FACTS_PREVIOUS_COLLECTION = "facts_previous"
CORPUS_ACTIVE_COLLECTION = "corpus"
CORPUS_STAGING_COLLECTION = "corpus_staging"
CORPUS_PREVIOUS_COLLECTION = "corpus_previous"
RETRIEVAL_TOP_K = 10
RETRIEVAL_MIN_SIMILARITY = 0.3
RETRIEVAL_HIGH_CONFIDENCE_SIMILARITY = 0.4
RETRIEVAL_EVIDENCE_STORE_FACTS = "facts"
RETRIEVAL_EVIDENCE_STORE_CORPUS = "corpus"
RETRIEVAL_TOOL_STATUS_INVALID = "invalid"
FACTS_REQUIRED_FIELDS = {"fact", "article_title", "source", "category", "published_at", "url"}
CORPUS_REQUIRED_FIELDS = {"title", "author", "source", "published_at", "category", "url", "body"}
FACTS_EXPECTED_RECORD_COUNT = 251
CORPUS_EXPECTED_RECORD_COUNT = 7629
FACTS_EXPECTED_RECORDS_SHA256 = "6c2bf19bf163930eb59b96c3d967aea1c21482811e42212893be7b4a7bae7820"
CORPUS_EXPECTED_RECORDS_SHA256 = "323a0dbe750ab62eb1672d548f9de283b0df7cd5e55901e479a92141f22ac5ff"
